version: "3.1"

services:

  mariadb-server:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb-server
      PMA_USER: root
      PMA_PASSWORD: 12345
    ports:
      - "8080:80"